import Head from "next/head"

interface LayoutProps {
  children: React.ReactNode;
}

const Layout = ({children}: LayoutProps ) => {
  return(
    <>
      <Head>
        <title>quoteThis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='min-h-screen bg-gray-100 py-6 flex flex-col justify-center align-center sm:py-12'>
        <div className="relative py-3 sm:max-w-xl sm:mx-auto">
        <h1 className='text-5xl py-4 font-bold'>Quote This</h1>
          { children }
        </div>  
      </div>
    </>
  )
}

export default Layout