import Head from 'next/head'

export default function Home() {
  return (
    <div className='w-screen h-screen flex justify-center items-center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-5xl font-bold'>Hello World</h1>
    </div>
  )
}
